services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zinc:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
    ports:
      - '4080:4080'
    networks:
      - my_network
    volumes:
      - ./zincsearch:/var/lib/zincsearch
  api:
    build:
      context: ./api
      args:
        API_PORT: ${API_PORT}
        APP_MODE: ${APP_MODE}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        ZINC_SEARCH_API_URL: ${ZINC_SEARCH_API_URL}
        ZINC_SEARCH_AGGREGATION_API_URL: ${ZINC_SEARCH_AGGREGATION_API_URL}
    environment:
      - ZINC_SEARCH_API_URL=${ZINC_SEARCH_API_URL}
      - ZINC_SEARCH_AGGREGATION_API_URL=${ZINC_SEARCH_AGGREGATION_API_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_PORT=${API_PORT}
    depends_on:
      - indexer
    networks:
      - my_network
  client:
    build:
      context: ./client
      args:
        VITE_API_URL: ${API_URL}
    environment:
      - VITE_API_URL=${API_URL}
    ports:
      - 80:8080
    networks:
      - my_network
    restart: on-failure
    depends_on:
      - api
networks:
  my_network:
    driver: bridge