services:
  zinc_search:
    image: public.ecr.aws/zinclabs/zinc:latest
    environment:
      - ZINC_SEARCH_ADMIN_USER=admin
      - ZINC_SEARCH_ADMIN_PASSWORD=Complexpass#123
    ports:
      - '4080:4080'
    networks:
      - my_network
    volumes:
      - ./zinc_search:/var/lib/zinc_search
  indexer:
    build:
      context: ./indexer
      args:
        DATA_PATH: ${DATA_PATH}
    environment:
      - ZINC_SEARCH_API_URL="http://localhost:4080/api/"
      - DB_USER="admin"
      - DB_PASSWORD="Complexpass#123"
    networks:
      - my_network
    restart: on-failure
    command: ["/bin/sh", "-c", "go run . $1"] # $1 is the argument passed to the command
  api:
    build:
      context: ./api
    ports:
      - 8080:8080
    environment:
      - ZINC_SEARCH_API_URL="http://localhost:4080/api/"
      - ZINC_SEARCH_AGGREGATION_API_URL="http://localhost:4080/es/"
      - DB_USER="admin"
      - DB_PASSWORD="Complexpass#123"
      - API_PORT=8080
    networks:
      - my_network
    restart: on-failure
  client:
    build:
      context: ./client
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - 80:8080
    networks:
      - my_network
    restart: on-failure
    depends_on:
      - api
  
networks:
  my_network:
    driver: bridge