###
GET http://localhost:8080/persons?page=7&page_size=10

###
GET http://localhost:8080/searchPersons?page=10&page_size=10&term=steve&field=email&sort=asc

###
GET http://localhost:8080/searchPersons?page=10&page_size=10&term=steve&field=name&sort=asc

###
GET http://localhost:8080/searchPersons?page=10&page_size=10&term=steve&field=_all&sort=asc