### 
GET http://localhost:8080/emails?page=1&page_size=10&sort=from&order=asc




###
GET http://localhost:8080/emails

### Email not found
GET http://localhost:8080/emails/2dYkolN9QoX


### EMAIL SUCESS
GET http://localhost:8080/emails/2e4GGzyUeyc





### EMAILS 
GET http://localhost:8080/emails?page=1&page_size=10&term=charles&field=from&sort=from&order=asc

### EMAILS 
GET http://localhost:8080/emails?page=45&page_size=100&term=charles&field=from&sort=asc

### EMAILS 
GET http://localhost:8080/emails