### 
GET http://localhost:8080/emails?page=1&page_size=2&sort=date&order=asc


###
GET http://localhost:8080/emails

### Email not found
GET http://localhost:8080/emails/2dYkolN9QoX


### EMAIL SUCESS
GET http://localhost:8080/emails/2e7hSmG5bO3





### EMAILS 
GET http://localhost:8080/emails?page=1&page_size=10&term=charles&field=from&sort=to&order=desc

### EMAILS 
GET http://localhost:8080/emails?page=503&page_size=20&sort=from&order=asc

### EMAILS 
GET http://localhost:8080/emails