###
GET http://localhost:8080/emails

### Email not found
GET http://localhost:8080/emails/2e7o7WQVlYKS

### 
GET http://localhost:8080/emails?page=1&page_size=3&sort=date&order=asc

### EMAILS 
GET http://localhost:8080/emails?page=1&page_size=15&term=charles&field=from&sort=to&order=desc
