services:
  api:
    build:
      context: .
      args:
        API_PORT: ${API_PORT}
        APP_MODE: ${APP_MODE}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        ZINC_SEARCH_API_URL: ${ZINC_SEARCH_API_URL}
        ZINC_SEARCH_AGGREGATION_API_URL: ${ZINC_SEARCH_AGGREGATION_API_URL}
    container_name: api
    environment:
      - ZINC_SEARCH_API_URL=${ZINC_SEARCH_API_URL}
      - ZINC_SEARCH_AGGREGATION_API_URL=${ZINC_SEARCH_AGGREGATION_API_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_PORT=${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
